sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t uptonm/docker-react -f ./client/Dockerfile.dev ./client/
scripts:
  - docker run uptonm/docker-react npm run test -- --coverage
