sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t uptonm/create-docker-workflow -f Dockerfile.dev .
scripts:
  - docker run uptonm/create-docker-workflow npm run test -- --coverage
