sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t uptonm/docker-react -f Dockerfile.dev .
scripts:
  - docker run uptonm/docker-react npm run test -- --coverage
