sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t uptonm/create-docker-workflow -f ./client/Dockerfile.dev ./client
scripts:
  - docker run uptonm/create-docker-workflow npm run test -- --coverage
